### ISSUE TITLE
Old transcription there isn't

### ISSUE THREAD

**Issue by Rufy86** [ASCIIwwdc/wwdc-session-transcripts#58]
I would need an old transcript. it is the transcription of Advanced Appearance Customization on iOS of WWDC 2012. session 216. how can I have it?

**Comment by natecook1000** [comment]
The 2012 sessions did not have captions, so only sessions that have been transcribed by the community and some donated transcriptions are available. If you do transcribe that video, we'd be happy to accept a pull request!
