### ISSUE TITLE
2015, session 604, Wayfinder demo sample code

### ISSUE THREAD

**Issue by damirstuhec** [ASCIIwwdc/wwdc-session-transcripts#62]
Does anybody know if there is a sample code of the demo project named Wayfinder shown in session 604?

https://github.com/ASCIIwwdc/wwdc-session-transcripts/blob/master/2015/604.vtt
https://developer.apple.com/videos/play/wwdc2015/604/

I'm interested in how they've built a fog particle system in that demo but I can't seem to find the sample code.

**Comment by capnslipp** [comment]
It doesn't look like the code for that one is available.  I couldn't find anything under https://developer.apple.com/library/prerelease/content/navigation/#section=Resource%20Types&topic=Sample%20Code nor https://github.com/robovm/apple-ios-samples that matches.

**Comment by damirstuhec** [comment]
Yeah, me neither. Thanks anyway!
