### ISSUE TITLE
Chinese Transcripts?

### ISSUE THREAD

**Issue by willard1218** [ASCIIwwdc/wwdc-session-transcripts#68]
Transcripts are English version,
I would like to download Chinese version.
But I change subtitles/eng/prog_index.m3u8 to subtitles/zh-tw/prog_index.m3u8
was doesn't work.

How can I download transcripts with Chinese version?

**Comment by rlwimi** [comment]
Unfortunately, English appears to be the only language in which Apple has captioned the videos.

**Comment by willard1218** [comment]
I notice that video has Chinese subtitle since 2015,
So I replace **subtitles/eng** with **subtitles/zho** in

https://github.com/ASCIIwwdc/wwdc-session-transcripts/blob/master/tools/fetch2016.rb#L47
https://github.com/ASCIIwwdc/wwdc-session-transcripts/blob/master/tools/fetch2016.rb#L50

then it's work !

**Comment by rlwimi** [comment]
Thanks for your persistence @willard1218. I think I looked at the 2017 videos, which were not captioned yet at the time, and didn't look further at previous year. 

See PR #72, and I'll work to support fetching them under [rlwimi/jonyfive issue #2](https://github.com/rlwimi/jonyfive/issues/2), though the same quick hack works there, as well.

**Comment by mattt** [comment]
Chinese transcripts are now available for 2015 – 2019. https://github.com/ASCIIwwdc/wwdc-session-transcripts/tree/master/zh-Hans
