### ISSUE TITLE
2014 Session 207: Clarify transcription text for footnoted items

### ISSUE THREAD

**Issue by danielpunkass** [ASCIIwwdc/wwdc-session-transcripts#74]
I came across the "accessibility compiler" transcription and footnote stating it was unclear whether it was "-Xcompiler". The interpretation that makes most sense if you listen to it is "Now Xcode's compiler will tell you..." (it sounds like "now Xcode compiler" but I think it's a linguistic artifact that it's not "Xcode's")

"https://github.com/ASCIIwwdc/wwdc-session-transcripts/blob/728c1243d8a3fee598d0a496667d6b574072da15/2014/207.vtt#L676

**Comment by danielpunkass** [comment]
While I'm in here I think I can clarify the other footnoted item in that file. The line marked [2] is not "forUIElement" but "FauxUIElement". That works in context and alludes to old sample code that uses this conventional naming.

**Comment by mattt** [comment]
Thanks for pointing this out, @danielpunkass. I've updated the transcript accordingly with ce23240.
